/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: VertaScan (https://sketchfab.com/VertaScan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/architectural-midhigh-rise-building-2dffaa30b8114acaa48bd91442091c0c
Title: Architectural Mid/High-Rise Building
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import Scene from '../assets/3d/building.glb'
import { a } from '@react-spring/three'



const Edificio = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
    const edificioRef = useRef()

    const { gl, viewport } = useThree();
    const { nodes, materials } = useGLTF(Scene);

    const lastX = useRef(0);
    const rotationSpeed = useRef(0);
    const dampingFactor = 0.95;

    //actions

    const handlePointerDown = (e) => {
        e.stopPropagation()
        e.preventDefault()
        setIsRotating(true)

        const clientX = e.touches
            ? e.touches[0].clientX
            : e.clientX

        lastX.current = clientX
    }

    const handlePointerUp = (e) => {
        e.stopPropagation()
        e.preventDefault()
        setIsRotating(false)


    }

    const handlePointerMove = (e) => {

        e.stopPropagation()
        e.preventDefault()

        if (isRotating) {
            const clientX = e.touches
                ? e.touches[0].clientX
                : e.clientX

            const delta = (clientX - lastX.current) / viewport.width

            edificioRef.current.rotation.y += delta * 0.01 * Math.PI
            lastX.current = clientX
            rotationSpeed.current = delta * 0.01 * Math.PI
        }

    }

    const handleKeyDown = (e) => {
        if (e.key === 'ArrowLeft') {
            if (!isRotating) setIsRotating(true);
            castleRef.current.rotation.y += 0.01 * Math.PI
        } else if (e.key === 'ArrowRight') {
            if (!isRotating) setIsRotating(true)
            castleRef.current.rotation.y -= 0.01 * Math.PI
        }
    }


    const handleKeyUp = (e) => {
        if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
            setIsRotating(false)
        }
    }

    useFrame(() => {
        if (!isRotating) {
            rotationSpeed.current *= dampingFactor

            if (Math.abs(rotationSpeed.current) < 0.001) {
                rotationSpeed.current = 0
            }

            edificioRef.current.rotation.y += rotationSpeed.current
        } else {
            const rotation = edificioRef.current.rotation.y

            const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI)

            //setea el actual estado basado en la orientacion del castillo

            switch (true) {
                case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
                    setCurrentStage(4)
                    break;
                case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
                    setCurrentStage(3)
                    break;
                case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
                    setCurrentStage(2)
                    break;
                case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
                    setCurrentStage(1)
                    break;


                default:
                    break;
            }
        }
    })



    useEffect(() => {
        const canvas = gl.domElement
        canvas.addEventListener('pointerdown', handlePointerDown)
        canvas.addEventListener('pointerup', handlePointerUp)
        canvas.addEventListener('pointermove', handlePointerMove)
        document.addEventListener('keydown', handleKeyDown)
        document.addEventListener('keyup', handleKeyUp)


        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown)
            canvas.removeEventListener('pointerup', handlePointerUp)
            canvas.removeEventListener('pointermove', handlePointerMove)
            document.removeEventListener('keydown', handleKeyDown)
            document.removeEventListener('keyup', handleKeyUp)
        }

    }, [gl, handlePointerDown, handlePointerMove, handlePointerUp])


    return (
        <a.group ref={edificioRef} {...props} dispose={null}>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.mullion}
                />
                <mesh


                    geometry={nodes.Object_5.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials.garage_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.site}
                />
            </group>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials.mullion}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.site}
                />
            </group>
            <group position={[0.497, 7.48, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials["ext_w-mat"]}
                />
            </group>
            <group position={[4.397, 8.98, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0.497, 10.48, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials.rail_glass}
                />
            </group>
            <group position={[0.497, 13.48, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 11.98, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_34.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 14.98, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_38.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 8.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_43.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 11.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_47.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_48.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 14.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_50.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_51.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_52.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[5.004, 16.48, 1.706]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_66.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_67.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_68.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_69.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_70.geometry}
                    material={materials.glass}
                />
            </group>
            <group position={[5.004, 19.48, 1.706]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_72.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_73.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_74.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_75.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_76.geometry}
                    material={materials.glass}
                />
            </group>
            <group position={[5.004, 22.48, 1.706]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_78.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_79.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_80.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_81.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_82.geometry}
                    material={materials.glass}
                />
            </group>
            <group position={[5.004, 25.48, 1.706]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_84.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_85.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_86.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_87.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_88.geometry}
                    material={materials.glass}
                />
            </group>
            <group position={[5.004, 28.48, 1.706]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_90.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_91.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_92.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_93.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_94.geometry}
                    material={materials.glass}
                />
            </group>
            <group position={[5.004, 31.48, 1.706]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_96.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_97.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_98.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_99.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_100.geometry}
                    material={materials.glass}
                />
            </group>
            <group position={[5.004, 34.48, 1.706]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_102.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_103.geometry}
                    material={materials.elev_door}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_104.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_105.geometry}
                    material={materials.site}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_106.geometry}
                    material={materials.int_wall_1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_107.geometry}
                    material={materials.glass}
                />
            </group>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_111.geometry}
                    material={materials.mullion}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_112.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_113.geometry}
                    material={materials.rail_glass}
                />
            </group>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_115.geometry}
                    material={materials.mullion}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_116.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_117.geometry}
                    material={materials.rail_glass}
                />
            </group>
            <group position={[0.497, 16.48, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_121.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_122.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_123.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0.497, 19.483, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_125.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_126.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_127.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0.497, 22.483, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_129.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_130.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_131.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0.497, 25.483, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_133.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_134.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_135.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0.497, 28.483, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_137.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_138.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_139.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0.497, 31.483, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_141.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_142.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_143.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 17.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_145.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_146.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_147.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 20.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_149.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_150.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_151.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 23.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_153.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_154.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_155.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 26.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_157.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_158.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_159.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 29.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_161.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_162.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_163.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 32.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_165.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_166.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_167.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.868, 35.98, 1.818]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_169.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_170.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_171.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0.497, 34.483, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_173.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_174.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_175.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 20.99, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_177.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_178.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_179.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 23.99, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_181.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_182.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_183.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 26.99, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_185.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_186.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_187.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 29.99, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_189.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_190.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_191.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 32.99, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_193.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_194.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_195.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[4.397, 35.99, 4.024]} scale={[1, 0.178, 1.997]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_197.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_198.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_199.geometry}
                    material={materials.mullion}
                />
            </group>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_219.geometry}
                    material={materials["ext_w-mat"]}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_220.geometry}
                    material={materials.rail_glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_221.geometry}
                    material={materials.mullion}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_222.geometry}
                    material={materials.site}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_223.geometry}
                    material={materials.leaves}
                />
            </group>
            <group position={[-0.007, 2.98, 3.823]} scale={19.939}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_225.geometry}
                    material={materials.site}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_226.geometry}
                    material={materials["ext_w-mat"]}
                />
            </group>
            <group position={[8.545, 2.991, 20.989]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_228.geometry}
                    material={materials.site}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_229.geometry}
                    material={materials.fl_light1}
                />
            </group>
            <group
                position={[12.045, 2.991, -2.561]}
                rotation={[-Math.PI, 0, -Math.PI]}
            >
                <mesh

                    receiveShadow
                    geometry={nodes.Object_231.geometry}
                    material={materials.site}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_232.geometry}
                    material={materials.fl_light1}
                />
            </group>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_282.geometry}
                    material={materials.mullion}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_283.geometry}
                    material={materials.fl_light1}
                />
            </group>
            <group position={[-8.001, 14.88, 5.996]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_285.geometry}
                    material={materials.fl_light1}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_286.geometry}
                    material={materials.light_frame}
                />
            </group>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_288.geometry}
                    material={materials.glass}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_289.geometry}
                    material={materials.rail_glass}
                />
            </group>
            <group position={[0, 7.48, 0]} scale={[10, 1.5, 7.5]}>
                <mesh

                    receiveShadow
                    geometry={nodes.Object_291.geometry}
                    material={materials.floor}
                />
                <mesh

                    receiveShadow
                    geometry={nodes.Object_292.geometry}
                    material={materials["ext_w-mat"]}
                />
            </group>
            <mesh

                receiveShadow
                geometry={nodes.Object_30.geometry}
                material={materials.yellow_steel}
                position={[2.5, 10.48, 3]}
                scale={[6.307, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_40.geometry}
                material={materials.fl_light1}
                position={[4.868, 8.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_45.geometry}
                material={materials.floor}
                position={[4.868, 11.98, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_54.geometry}
                material={materials.floor}
                position={[4.868, 8.98, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_56.geometry}
                material={materials.fl_light1}
                position={[4.868, 11.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_58.geometry}
                material={materials.fl_light1}
                position={[4.868, 14.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_60.geometry}
                material={materials.floor}
                position={[9, 8.98, 6.175]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_62.geometry}
                material={materials.yellow_steel}
                position={[2.5, 10.48, 4]}
                scale={[6.307, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_64.geometry}
                material={materials.yellow_steel}
                position={[2.5, 10.48, 5]}
                scale={[6.307, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_109.geometry}
                material={materials["ext_w-mat"]}
                position={[-9.637, 6.264, -7.051]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_119.geometry}
                material={materials.fl_light1}
                position={[4.868, 38.851, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_201.geometry}
                material={materials.elev_door}
                position={[6.875, 7.48, 2]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_203.geometry}
                material={materials.fl_light1}
                position={[4.868, 17.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_205.geometry}
                material={materials.fl_light1}
                position={[4.868, 20.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_207.geometry}
                material={materials.fl_light1}
                position={[4.868, 23.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_209.geometry}
                material={materials.fl_light1}
                position={[4.868, 26.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_211.geometry}
                material={materials.fl_light1}
                position={[4.868, 29.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_213.geometry}
                material={materials.fl_light1}
                position={[4.868, 32.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_215.geometry}
                material={materials.fl_light1}
                position={[4.868, 35.921, 1.818]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_217.geometry}
                material={materials.grass}
                position={[-8.011, 3.04, 20.043]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_234.geometry}
                material={materials.floor}
                position={[0, 7.48, 0]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_236.geometry}
                material={materials.leaves}
                position={[0, 7.48, 0]}
                scale={[10, 1.5, 7.5]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_238.geometry}
                material={materials.rock_material}
                position={[-6.397, 4.019, 20.43]}
                scale={2.282}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_240.geometry}
                material={materials.rock_material}
                position={[-11.058, 3.395, 18.964]}
                scale={[2.132, 0.82, 2.488]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_242.geometry}
                material={materials.rock_material}
                position={[-8.95, 3.488, 20.06]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1.486, 2.129, 2.129]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_244.geometry}
                material={materials.rock_material}
                position={[-7.697, 4.319, 20.23]}
                rotation={[0, Math.PI / 2, 0]}
                scale={1.631}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_246.geometry}
                material={materials.rock_material}
                position={[-4.397, 3.541, 20.836]}
                rotation={[0, 0.927, 0]}
                scale={[1.976, 1.499, 1.976]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_248.geometry}
                material={materials.Leaf}
                position={[10.782, 7.181, 16.661]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_250.geometry}
                material={materials.Leaf}
                position={[12.082, 7.181, 16.661]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_252.geometry}
                material={materials.Leaf}
                position={[13.382, 7.181, 16.661]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_254.geometry}
                material={materials.Leaf}
                position={[13.422, 7.181, 15.283]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_256.geometry}
                material={materials.Leaf}
                position={[13.422, 7.181, 13.883]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_258.geometry}
                material={materials.Leaf}
                position={[13.422, 7.181, 12.383]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_260.geometry}
                material={materials.Leaf}
                position={[-9.018, 4.281, 17.361]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_262.geometry}
                material={materials.Leaf}
                position={[-10.118, 4.281, 17.761]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_264.geometry}
                material={materials.Leaf}
                position={[-8.018, 4.281, 18.061]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_266.geometry}
                material={materials.Leaf}
                position={[-6.918, 4.281, 18.761]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_268.geometry}
                material={materials.Leaf}
                position={[-5.718, 4.281, 19.161]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_270.geometry}
                material={materials.Leaf}
                position={[-2.918, 4.281, 21.061]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_272.geometry}
                material={materials.Leaf}
                position={[-5.518, 4.281, 21.561]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_274.geometry}
                material={materials.Leaf}
                position={[-7.118, 4.281, 21.561]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_276.geometry}
                material={materials.Leaf}
                position={[-8.618, 4.281, 21.561]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_278.geometry}
                material={materials.Leaf}
                position={[-10.218, 4.281, 21.461]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_280.geometry}
                material={materials.Leaf}
                position={[-11.218, 4.281, 20.561]}
                scale={[0.382, 1.458, 0.401]}
            />
            <mesh

                receiveShadow
                geometry={nodes.Object_294.geometry}
                material={materials.floor}
                position={[0, 7.48, 0]}
                scale={[10, 1.5, 7.5]}
            />
        </a.group>
    );
}



export default Edificio;
